"""empty message

Revision ID: 68d46e99a842
Revises: fe4b1be23ed8
Create Date: 2025-06-21 16:14:51.427256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d46e99a842'
down_revision = 'fe4b1be23ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=80), nullable=True))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('eye_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
