"""empty message

Revision ID: d451e904ad79
Revises: 68d46e99a842
Create Date: 2025-06-25 00:45:23.043395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd451e904ad79'
down_revision = '68d46e99a842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_characters')
    op.drop_table('user_planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='user_planets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_planets_pkey')
    )
    op.create_table('user_characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='user_characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_characters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_characters_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
